"use client";
import { Search } from "lucide-react";
import { useMemo, useState } from "react";
import { viewportDefinitions } from "@/lib/analyzer/types";
import type { AnalysisReport, Severity, ViewportId } from "@/lib/analyzer/types";
import { ViolationItem } from "./violation-item";
export function ViolationsList({ report }: { report: AnalysisReport }) {
  const [query, setQuery] = useState(""); const [filter, setFilter] = useState<Severity | "all">("all"); const [viewport, setViewport] = useState<ViewportId | "all">("all");
  const items = useMemo(() => report.violations.filter((item) => (filter === "all" || item.impact === filter) && (viewport === "all" || item.viewportId === viewport) && `${item.id} ${item.title} ${item.description}`.toLowerCase().includes(query.toLowerCase())), [filter, query, report.violations, viewport]);
  const selectedViewports = report.viewportReports.map((item) => item.viewport.id);
  return <section className="mt-8 rounded-2xl border border-slate-200 bg-white p-4 shadow-sm sm:p-6"><div className="flex flex-col justify-between gap-4 border-b border-slate-100 pb-5 sm:flex-row sm:items-center"><div><p className="text-[10px] font-bold uppercase tracking-[.14em] text-slate-400">جزئیات فنی</p><h2 className="mt-1 text-xl font-bold text-slate-900">فهرست موارد قابل اصلاح</h2><p className="mt-1 text-xs text-slate-500">{items.length} مورد مطابق جستجو و فیلتر فعلی</p></div><div className="flex flex-wrap gap-2"><label className="relative"><Search size={16} className="absolute right-3 top-3 text-slate-400" /><input aria-label="جستجوی خطاها" value={query} onChange={(event) => setQuery(event.target.value)} placeholder="جستجو" className="focus-ring h-10 w-40 rounded-lg border border-slate-200 bg-slate-50 pr-9 text-sm text-slate-800 shadow-sm placeholder:text-slate-400 transition hover:bg-white focus:bg-white" /></label><select aria-label="فیلتر شدت" value={filter} onChange={(event) => setFilter(event.target.value as Severity | "all")} className="focus-ring rounded-lg border border-slate-200 bg-slate-50 px-2 text-sm text-slate-700 shadow-sm transition hover:bg-white"><option value="all">همه شدت‌ها</option><option value="critical">بحرانی</option><option value="serious">جدی</option><option value="moderate">متوسط</option><option value="minor">جزئی</option></select>{selectedViewports.length > 1 && <select aria-label="فیلتر اندازه صفحه" value={viewport} onChange={(event) => setViewport(event.target.value as ViewportId | "all")} className="focus-ring rounded-lg border border-slate-200 bg-slate-50 px-2 text-sm text-slate-700 shadow-sm transition hover:bg-white"><option value="all">همه نمایش‌ها</option>{selectedViewports.map((id) => <option key={id} value={id}>{viewportDefinitions[id].name}</option>)}</select>}</div></div><div className="mt-5 space-y-3">{items.length ? items.map((item, index) => <ViolationItem key={`${item.id}-${index}`} violation={item} />) : <div className="rounded-xl border border-dashed border-slate-300 bg-slate-50 p-8 text-center text-slate-500">موردی با این فیلتر پیدا نشد.</div>}</div></section>;
}
