"use client";
import { Check, ChevronDown, Copy } from "lucide-react";
import { useState } from "react";
import type { AnalyzerViolation } from "@/lib/analyzer/types";
export function ViolationItem({ violation }: { violation: AnalyzerViolation }) {
  const [open, setOpen] = useState(false); const [copied, setCopied] = useState(false);
  const copy = async (value: string) => { await navigator.clipboard?.writeText(value); setCopied(true); setTimeout(() => setCopied(false), 1200); };
  return <article className="rounded-xl border border-zinc-800 bg-zinc-900"><button type="button" onClick={() => setOpen(!open)} aria-expanded={open} className="focus-ring flex w-full items-center justify-between gap-4 p-5 text-right"><span><span className="block font-bold">{violation.title}</span><span className="mt-2 block text-xs text-zinc-500">{violation.id} · {violation.source} · {violation.impact}</span></span><ChevronDown className={`shrink-0 transition ${open ? "rotate-180" : ""}`} size={18} /></button>{open && <div className="border-t border-zinc-800 p-5 text-sm leading-7 text-zinc-300"><p>{violation.description}</p><p className="mt-3 text-violet-300">راهکار: {violation.fixSuggestion}</p>{violation.wcag.length > 0 && <p className="mt-2 text-zinc-500">WCAG: {violation.wcag.join("، ")}</p>}<div className="mt-4 space-y-3">{violation.nodes.map((node, index) => <div key={`${node.target.join("-")}-${index}`} className="rounded-lg bg-zinc-950 p-3"><div className="flex items-center justify-between gap-3"><code className="ltr break-all text-xs text-violet-300">{node.target.join(", ")}</code><button type="button" aria-label="کپی HTML" onClick={() => copy(node.html)} className="focus-ring shrink-0 rounded p-1 text-zinc-500 hover:text-white">{copied ? <Check size={15} /> : <Copy size={15} />}</button></div><pre className="ltr mt-2 max-h-28 overflow-auto whitespace-pre-wrap break-all text-xs text-zinc-400">{node.html}</pre><p className="mt-2 text-xs text-zinc-500">{node.failureSummary}</p></div>)}</div>{violation.helpUrl && <a className="mt-4 inline-block text-violet-300 underline" href={violation.helpUrl} target="_blank" rel="noopener noreferrer">مرجع راهنما</a>}</div>}</article>;
}
