"use client";
import { Check, Clipboard, ExternalLink } from "lucide-react";
import { useState } from "react";
import type { AnalyzerViolation } from "@/lib/analyzer/types";
const labels = { critical: "بحرانی", serious: "جدی", moderate: "متوسط", minor: "جزئی" };
const colors = { critical: "border-red-500/30 bg-red-500/10 text-red-300", serious: "border-orange-500/30 bg-orange-500/10 text-orange-300", moderate: "border-yellow-500/30 bg-yellow-500/10 text-yellow-300", minor: "border-blue-500/30 bg-blue-500/10 text-blue-300" };
export function ViolationItem({ violation }: { violation: AnalyzerViolation }) {
  const [copied, setCopied] = useState(false); const snippet = violation.nodes[0]?.html ?? "";
  const copy = async () => { await navigator.clipboard.writeText(snippet); setCopied(true); setTimeout(() => setCopied(false), 1500); };
  return <details className="group rounded-xl border border-zinc-800 bg-zinc-900"><summary className="flex cursor-pointer list-none items-center gap-3 p-4"><span className={`rounded-full border px-2 py-1 text-xs ${colors[violation.impact]}`}>{labels[violation.impact]}</span><span className="flex-1 text-sm font-semibold">{violation.title}</span><span className="text-xs text-zinc-500">{violation.nodes.length} مورد</span></summary><div className="border-t border-zinc-800 p-5 text-sm"><div className="grid gap-4 text-zinc-400 sm:grid-cols-2"><p><span className="text-zinc-600">WCAG:</span> {violation.wcag.length ? violation.wcag.join("، ") : "—"}</p><p><span className="text-zinc-600">منبع:</span> {violation.source === "axe-core" ? "axe-core" : "قانون اختصاصی"}</p></div><p className="mt-4 leading-7 text-zinc-300">{violation.description}</p><div className="mt-4 rounded-lg border border-zinc-800 bg-zinc-950 p-3"><div className="mb-2 flex items-center justify-between text-xs text-zinc-500"><span className="ltr">{violation.nodes[0]?.target.join(" ")}</span><button type="button" onClick={copy} className="focus-ring flex items-center gap-1 text-violet-300">{copied ? <Check size={14} /> : <Clipboard size={14} />} {copied ? "کپی شد" : "کپی HTML"}</button></div><pre className="max-h-36 overflow-auto whitespace-pre-wrap text-xs text-zinc-300">{snippet}</pre></div><p className="mt-4 rounded-lg bg-zinc-800/50 p-3 leading-7 text-zinc-400"><strong className="text-zinc-200">راهکار: </strong>{violation.fixSuggestion}</p>{violation.helpUrl && <a href={violation.helpUrl} target="_blank" rel="noopener noreferrer" className="focus-ring mt-4 inline-flex items-center gap-1 text-xs text-violet-300 hover:text-violet-200">مرجع WCAG <ExternalLink size={13} /></a>}</div></details>;
}
