import type { Page } from "playwright";
import type { AnalyzerNode, AnalyzerViolation, Severity } from "./types";

type RawFinding = { id: string; impact: Severity; wcag: string[]; title: string; description: string; help: string; helpUrl?: string; fixSuggestion: string; nodes: AnalyzerNode[] };
export async function runCustomRules(page: Page): Promise<AnalyzerViolation[]> {
  const findings = await page.evaluate((): RawFinding[] => {
    const node = (target: string, html: string, failureSummary: string): AnalyzerNode => ({ target: [target], html, failureSummary });
    const selector = (element: Element, index: number): string => {
      if (element.id) return `#${CSS.escape(element.id)}`;
      const tag = element.tagName.toLowerCase();
      const classes = [...element.classList].slice(0, 2).map((name) => `.${CSS.escape(name)}`).join("");
      return `${tag}${classes || `:nth-of-type(${index + 1})`}`;
    };
    const results: RawFinding[] = [];
    const add = (finding: Omit<RawFinding, "nodes">, nodes: AnalyzerNode[]) => results.push({ ...finding, nodes });
    const html = document.documentElement;
    if (!html.getAttribute("lang")) add({ id: "missing-html-lang", impact: "serious", wcag: ["3.1.1"], title: "زبان صفحه مشخص نشده است", description: "ویژگی lang برای تشخیص زبان محتوا توسط صفحه‌خوان لازم است.", help: "زبان اصلی صفحه را مشخص کنید.", fixSuggestion: '<html lang="fa" dir="rtl">', helpUrl: "https://www.w3.org/WAI/WCAG22/Understanding/language-of-page.html" }, [node("html", html.outerHTML.slice(0, 300), "ویژگی lang در html وجود ندارد.")]);
    if ((html.getAttribute("lang") ?? "").toLowerCase().startsWith("fa") && html.getAttribute("dir") !== "rtl") add({ id: "missing-rtl-direction", impact: "minor", wcag: [], title: "جهت راست‌به‌چپ مشخص نشده است", description: "برای محتوای فارسی، dir=\"rtl\" نمایش و سازگاری رابط را بهتر می‌کند.", help: "جهت صفحه را روی rtl تنظیم کنید.", fixSuggestion: '<html lang="fa" dir="rtl">', }, [node("html", html.outerHTML.slice(0, 300), "صفحه فارسی است اما dir=rtl ندارد.")]);
    if (!document.title.trim()) add({ id: "missing-page-title", impact: "serious", wcag: ["2.4.2"], title: "عنوان صفحه وجود ندارد", description: "title به کاربران و صفحه‌خوان‌ها برای تشخیص موضوع صفحه کمک می‌کند.", help: "برای صفحه عنوانی کوتاه و توصیفی تعیین کنید.", fixSuggestion: "<title>عنوان توصیفی صفحه</title>", helpUrl: "https://www.w3.org/WAI/WCAG22/Understanding/page-titled.html" }, [node("head", document.head.outerHTML.slice(0, 300), "عنوان صفحه خالی یا غایب است.")]);
    const headings = [...document.querySelectorAll("h1,h2,h3,h4,h5,h6")];
    if (!document.querySelector("h1")) add({ id: "missing-h1", impact: "moderate", wcag: ["1.3.1"], title: "Heading اصلی وجود ندارد", description: "صفحه باید یک heading سطح اول برای معرفی موضوع اصلی داشته باشد.", help: "یک h1 توصیفی اضافه کنید.", fixSuggestion: "<h1>عنوان اصلی صفحه</h1>" }, [node("body", "<body>", "هیچ h1 در صفحه پیدا نشد.")]);
    if (headings.filter((item) => item.tagName === "H1").length > 1) add({ id: "multiple-h1", impact: "moderate", wcag: ["1.3.1"], title: "چند Heading اصلی وجود دارد", description: "وجود چند h1 می‌تواند ساختار صفحه را برای کاربران فناوری کمکی مبهم کند.", help: "یک h1 اصلی نگه دارید و برای بخش‌ها از h2 استفاده کنید.", fixSuggestion: "Headingهای اضافی را به h2 یا سطح مناسب تبدیل کنید." }, headings.filter((item) => item.tagName === "H1").map((item, i) => node(selector(item, i), item.outerHTML, "چند h1 در صفحه وجود دارد.")));
    headings.forEach((item, i) => { const current = Number(item.tagName.substring(1)); const previous = i ? Number(headings[i - 1].tagName.substring(1)) : current; if (current > previous + 1) add({ id: "heading-order", impact: "moderate", wcag: ["1.3.1"], title: "پرش در ترتیب Headingها", description: "سطح heading بدون رعایت ترتیب منطقی افزایش یافته است.", help: "سطح headingها را به‌صورت سلسله‌مراتبی مرتب کنید.", fixSuggestion: "برای مثال h1 را مستقیماً به h3 تبدیل نکنید؛ ابتدا h2 را قرار دهید." }, [node(selector(item, i), item.outerHTML, `ترتیب از h${previous} به h${current} پرش کرده است.`)]); });
    document.querySelectorAll("img").forEach((item, i) => { if (!item.hasAttribute("alt")) add({ id: "image-alt", impact: "critical", wcag: ["1.1.1"], title: "تصویر بدون متن جایگزین", description: "تصویر معنادار باید متنی داشته باشد که هدف یا محتوای آن را توصیف کند.", help: "برای تصویر ویژگی alt معنادار اضافه کنید.", fixSuggestion: 'برای نمونه alt="بنر معرفی خدمات سامانه" اضافه کنید.', helpUrl: "https://www.w3.org/WAI/WCAG22/Understanding/non-text-content.html" }, [node(selector(item, i), item.outerHTML, "Element does not have an alt attribute.")]); else if (!item.getAttribute("alt")?.trim()) add({ id: "empty-image-alt", impact: "minor", wcag: ["1.1.1"], title: "متن جایگزین تصویر خالی است", description: "ممکن است تصویر تزئینی باشد؛ قضاوت نهایی نیازمند بررسی انسانی است.", help: "اگر تصویر تزئینی است alt=\"\" مناسب است، در غیر این صورت متن توصیفی اضافه کنید.", fixSuggestion: "مناسب بودن تزئینی بودن تصویر را بررسی کنید." }, [node(selector(item, i), item.outerHTML, "alt attribute is empty.")]); });
    const vague = new Set(["اینجا", "اینجا کلیک کنید", "بیشتر", "ادامه", "مشاهده", "click here", "more", "read more", "learn more"]);
    document.querySelectorAll("a").forEach((item, i) => { const name = (item.getAttribute("aria-label") || item.textContent || "").replace(/\s+/g, " ").trim().toLowerCase(); if (vague.has(name)) add({ id: "ambiguous-link-text", impact: "moderate", wcag: ["2.4.4"], title: "متن لینک مبهم است", description: "متن لینک به‌تنهایی مقصد یا اقدام مورد انتظار را روشن نمی‌کند.", help: "متن لینک باید مقصد یا موضوع را واضح بیان کند.", fixSuggestion: 'مثلاً «مطالعه مقاله راهنمای دسترس‌پذیری وب» بنویسید.', helpUrl: "https://www.w3.org/WAI/WCAG22/Understanding/link-purpose-in-context.html" }, [node(selector(item, i), item.outerHTML, "متن لینک عمومی و مبهم است.")]); if (item.getAttribute("target") === "_blank" && !(item.getAttribute("rel") ?? "").toLowerCase().split(/\s+/).includes("noopener")) add({ id: "blank-target-noopener", impact: "minor", wcag: [], title: "لینک target=_blank بدون noopener", description: "این یک هشدار امنیتی/کیفی است و نقض قطعی WCAG محسوب نمی‌شود.", help: "برای لینک‌های جدید noopener اضافه کنید.", fixSuggestion: '<a target="_blank" rel="noopener noreferrer">', }, [node(selector(item, i), item.outerHTML, "target=_blank بدون rel=noopener است.")]); });
    document.querySelectorAll("input,select,textarea").forEach((item, i) => { const labeled = item.hasAttribute("aria-label") || item.hasAttribute("aria-labelledby") || (!!item.id && !!document.querySelector(`label[for="${CSS.escape(item.id)}"]`)); if (!labeled) add({ id: "form-control-name", impact: "serious", wcag: ["1.3.1", "4.1.2"], title: "عنصر فرم برچسب ندارد", description: "کنترل فرم باید accessible name قابل تشخیص برای کاربران فناوری کمکی داشته باشد.", help: "یک label مرتبط یا aria-label اضافه کنید.", fixSuggestion: '<label for="email">ایمیل</label>', helpUrl: "https://www.w3.org/WAI/WCAG22/Understanding/labels-or-instructions.html" }, [node(selector(item, i), item.outerHTML, "Form control has no accessible label.")]); });
    document.querySelectorAll("button,[role=\"button\"]").forEach((item, i) => { const name = (item.getAttribute("aria-label") || item.getAttribute("aria-labelledby") || item.textContent || "").trim(); if (!name) add({ id: "button-name", impact: "critical", wcag: ["4.1.2"], title: "دکمه نام قابل دسترس ندارد", description: "دکمه باید نامی داشته باشد تا صفحه‌خوان عملکرد آن را اعلام کند.", help: "متن داخلی یا aria-label توصیفی اضافه کنید.", fixSuggestion: '<button type="button">ارسال فرم</button>', helpUrl: "https://www.w3.org/WAI/WCAG22/Understanding/name-role-value.html" }, [node(selector(item, i), item.outerHTML, "Button has no accessible name.")]); if (item.matches("[role=\"button\"]") && item.tagName !== "BUTTON" && item.getAttribute("tabindex") !== "0") add({ id: "non-semantic-interactive", impact: "serious", wcag: ["2.1.1", "4.1.2"], title: "عنصر تعاملی غیرمعنایی است", description: "عنصر دارای role=button باید با کیبورد قابل دسترسی باشد.", help: "از button واقعی استفاده کنید.", fixSuggestion: '<button type="button">ارسال فرم</button>', helpUrl: "https://www.w3.org/WAI/WCAG22/Understanding/keyboard.html" }, [node(selector(item, i), item.outerHTML, "Non-native button is not keyboard focusable.")]); });
    document.querySelectorAll("div[onclick],span[onclick]").forEach((item, i) => add({ id: "non-semantic-clickable", impact: "serious", wcag: ["2.1.1"], title: "عنصر کلیک‌پذیر غیرمعنایی", description: "تشخیص event listener از DOM کامل نیست؛ این مورد بر اساس onclick قابل مشاهده گزارش شده است.", help: "به‌جای div یا span از button یا link استفاده کنید.", fixSuggestion: '<button type="button">عملیات</button>' }, [node(selector(item, i), item.outerHTML, "Clickable element is a div or span.")]));
    return results;
  });
  return findings.map((item) => ({ ...item, source: "custom" as const }));
}
